"""capture metadata + dossiers

Revision ID: 5195aae781ff
Revises: a2b58730cc76
Create Date: 2026-06-18 11:10:20.623474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5195aae781ff'
down_revision: Union[str, Sequence[str], None] = 'a2b58730cc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('chapter', sa.String(length=255), nullable=False),
    sa.Column('notes_md', sa.Text(), nullable=True),
    sa.Column('notes_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'subject', 'chapter', name='uq_dossier_user_subject_chapter')
    )
    op.create_index(op.f('ix_dossiers_user_id'), 'dossiers', ['user_id'], unique=False)
    op.add_column('user_pages', sa.Column('subject', sa.String(length=255), nullable=True))
    op.add_column('user_pages', sa.Column('chapter', sa.String(length=255), nullable=True))
    op.add_column('user_pages', sa.Column('page_no', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_pages_subject'), 'user_pages', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_pages_subject'), table_name='user_pages')
    op.drop_column('user_pages', 'page_no')
    op.drop_column('user_pages', 'chapter')
    op.drop_column('user_pages', 'subject')
    op.drop_index(op.f('ix_dossiers_user_id'), table_name='dossiers')
    op.drop_table('dossiers')
    # ### end Alembic commands ###
