"""challenges and social schema

Revision ID: a2b58730cc76
Revises: baea3fbcf09f
Create Date: 2026-06-18 10:21:00.314878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2b58730cc76'
down_revision: Union[str, Sequence[str], None] = 'baea3fbcf09f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_content_hash', sa.String(length=64), nullable=False),
    sa.Column('scoring_rule_json', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_creator_user_id'), 'challenges', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_challenges_source_content_hash'), 'challenges', ['source_content_hash'], unique=False)
    op.create_table('feed_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('ref_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_events_actor_user_id'), 'feed_events', ['actor_user_id'], unique=False)
    op.create_index('ix_feed_events_created_at', 'feed_events', ['created_at'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('addressee_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_user_id', 'addressee_user_id', name='uq_friendship_pair')
    )
    op.create_index(op.f('ix_friendships_addressee_user_id'), 'friendships', ['addressee_user_id'], unique=False)
    op.create_index(op.f('ix_friendships_requester_user_id'), 'friendships', ['requester_user_id'], unique=False)
    op.create_table('shared_decks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'content_hash', name='uq_shared_deck_owner_hash')
    )
    op.create_index(op.f('ix_shared_decks_content_hash'), 'shared_decks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_shared_decks_owner_user_id'), 'shared_decks', ['owner_user_id'], unique=False)
    op.create_table('challenge_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_correct', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_attempts_challenge_id'), 'challenge_attempts', ['challenge_id'], unique=False)
    op.create_index('ix_challenge_attempts_challenge_score', 'challenge_attempts', ['challenge_id', 'score'], unique=False)
    op.create_index(op.f('ix_challenge_attempts_user_id'), 'challenge_attempts', ['user_id'], unique=False)
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feed_event_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['feed_event_id'], ['feed_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feed_event_id', 'reaction_type', name='uq_reaction_user_event_type')
    )
    op.create_index(op.f('ix_reactions_feed_event_id'), 'reactions', ['feed_event_id'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_feed_event_id'), table_name='reactions')
    op.drop_table('reactions')
    op.drop_index(op.f('ix_challenge_attempts_user_id'), table_name='challenge_attempts')
    op.drop_index('ix_challenge_attempts_challenge_score', table_name='challenge_attempts')
    op.drop_index(op.f('ix_challenge_attempts_challenge_id'), table_name='challenge_attempts')
    op.drop_table('challenge_attempts')
    op.drop_index(op.f('ix_shared_decks_owner_user_id'), table_name='shared_decks')
    op.drop_index(op.f('ix_shared_decks_content_hash'), table_name='shared_decks')
    op.drop_table('shared_decks')
    op.drop_index(op.f('ix_friendships_requester_user_id'), table_name='friendships')
    op.drop_index(op.f('ix_friendships_addressee_user_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index('ix_feed_events_created_at', table_name='feed_events')
    op.drop_index(op.f('ix_feed_events_actor_user_id'), table_name='feed_events')
    op.drop_table('feed_events')
    op.drop_index(op.f('ix_challenges_source_content_hash'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_creator_user_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
