import React, { useEffect, useState } from "react";
import { getDeck } from "../api.js";
import Deck from "../components/Deck.jsx";

export default function DeckView({ hash, onBack, onUnauthorized }) {
  const [state, setState] = useState({ loading: true, deck: null, error: "" });

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const res = await getDeck(hash);
        if (alive) setState({ loading: false, deck: res, error: "" });
      } catch (err) {
        if (err.status === 401) {
          onUnauthorized();
          return;
        }
        if (alive) {
          setState({
            loading: false,
            deck: null,
            error: err.status === 404 ? "This deck isn't available." : "Couldn't load this deck.",
          });
        }
      }
    })();
    return () => { alive = false; };
  }, [hash, onUnauthorized]);

  return (
    <div>
      <button className="btn-ghost" onClick={onBack} style={{ marginBottom: 14 }}>‹ Back to decks</button>
      {state.loading && (
        <div className="card loading-wrap">
          <div className="spinner" />
          <p>Loading deck…</p>
        </div>
      )}
      {state.error && <p className="error">{state.error}</p>}
      {state.deck && (
        <>
          <Deck flashcards={state.deck.flashcards} quiz={state.deck.quiz} />
          {state.deck.model_used && state.deck.model_used !== "none" && (
            <p className="muted center">generated by {state.deck.model_used}</p>
          )}
        </>
      )}
    </div>
  );
}
