import React, { useEffect, useState } from "react";
import { getDeck, shareDeck } from "../api.js";
import Deck from "../components/Deck.jsx";

export default function DeckView({ hash, onBack, onUnauthorized }) {
  const [state, setState] = useState({ loading: true, deck: null, error: "" });
  const [share, setShare] = useState({ busy: false, msg: null }); // msg: {ok, text}

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const res = await getDeck(hash);
        if (alive) setState({ loading: false, deck: res, error: "" });
      } catch (err) {
        if (err.status === 401) {
          onUnauthorized();
          return;
        }
        if (alive) {
          setState({
            loading: false,
            deck: null,
            error: err.status === 404 ? "This deck isn't available." : "Couldn't load this deck.",
          });
        }
      }
    })();
    return () => { alive = false; };
  }, [hash, onUnauthorized]);

  async function doShare() {
    setShare({ busy: true, msg: null });
    try {
      const res = await shareDeck({ content_hash: hash, visibility: "friends" });
      setShare({
        busy: false,
        msg: { ok: true, text: res.created === false ? "Already shared with your friends." : "Shared with your friends! 🎉" },
      });
    } catch (err) {
      if (err.status === 401) { onUnauthorized(); return; }
      setShare({ busy: false, msg: { ok: false, text: "Couldn't share this deck." } });
    }
  }

  return (
    <div>
      <button className="btn-ghost" onClick={onBack} style={{ marginBottom: 14 }}>‹ Back to decks</button>
      {state.loading && (
        <div className="card loading-wrap">
          <div className="spinner" />
          <p>Loading deck…</p>
        </div>
      )}
      {state.error && <p className="error">{state.error}</p>}
      {state.deck && (
        <>
          <div className="card share-bar">
            <div>
              <div style={{ fontWeight: 600 }}>Study with friends</div>
              <div className="meta">Share this deck so your crew can revise it too.</div>
            </div>
            <button className="btn-primary auto" disabled={share.busy} onClick={doShare}>
              {share.busy ? "Sharing…" : "📤 Share"}
            </button>
          </div>
          {share.msg && <p className={share.msg.ok ? "ok-msg" : "error"}>{share.msg.text}</p>}
          <Deck flashcards={state.deck.flashcards} quiz={state.deck.quiz} />
          {state.deck.model_used && state.deck.model_used !== "none" && (
            <p className="muted center">generated by {state.deck.model_used}</p>
          )}
        </>
      )}
    </div>
  );
}
