import React, { useEffect, useState } from "react";
import { getDeck, shareDeck } from "../api.js";
import Deck from "../components/Deck.jsx";

const SHARE_BASE = "https://yaad.engstech.com/shared/";

export default function DeckView({ hash, onBack, onUnauthorized, backLabel = "Back to library" }) {
  const [state, setState] = useState({ loading: true, deck: null, error: "" });
  const [share, setShare] = useState({ busy: false, msg: null }); // msg: {ok, text}
  const [link, setLink] = useState({ busy: false, url: null, copied: false, error: "" });

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const res = await getDeck(hash);
        if (alive) setState({ loading: false, deck: res, error: "" });
      } catch (err) {
        if (err.status === 401) {
          onUnauthorized();
          return;
        }
        if (alive) {
          setState({
            loading: false,
            deck: null,
            error: err.status === 404 ? "This deck isn't available." : "Couldn't load this deck.",
          });
        }
      }
    })();
    return () => { alive = false; };
  }, [hash, onUnauthorized]);

  async function doShare() {
    setShare({ busy: true, msg: null });
    try {
      const res = await shareDeck({ content_hash: hash, visibility: "friends" });
      setShare({
        busy: false,
        msg: { ok: true, text: res.created === false ? "Already shared with your friends." : "Shared with your friends! 🎉" },
      });
    } catch (err) {
      if (err.status === 401) { onUnauthorized(); return; }
      setShare({ busy: false, msg: { ok: false, text: "Couldn't share this deck." } });
    }
  }

  async function doShareLink() {
    setLink({ busy: true, url: null, copied: false, error: "" });
    try {
      const res = await shareDeck({ content_hash: hash, visibility: "link" });
      setLink({ busy: false, url: SHARE_BASE + res.content_hash, copied: false, error: "" });
    } catch (err) {
      if (err.status === 401) { onUnauthorized(); return; }
      setLink({ busy: false, url: null, copied: false, error: "Couldn't create a share link." });
    }
  }

  async function copyUrl() {
    try {
      await navigator.clipboard.writeText(link.url);
      setLink((l) => ({ ...l, copied: true }));
    } catch {
      setLink((l) => ({ ...l, copied: false }));
    }
  }

  return (
    <div>
      <button className="btn-ghost" onClick={onBack} style={{ marginBottom: 14 }}>‹ {backLabel}</button>
      {state.loading && (
        <div className="card loading-wrap">
          <div className="spinner" />
          <p>Loading deck…</p>
        </div>
      )}
      {state.error && <p className="error">{state.error}</p>}
      {state.deck && (
        <>
          <div className="card share-bar">
            <div>
              <div style={{ fontWeight: 600 }}>Study with friends</div>
              <div className="meta">Share this deck so your crew can revise it too.</div>
            </div>
            <button className="btn-primary auto" disabled={share.busy} onClick={doShare}>
              {share.busy ? "Sharing…" : "📤 Share"}
            </button>
          </div>
          {share.msg && <p className={share.msg.ok ? "ok-msg" : "error"}>{share.msg.text}</p>}

          <div className="card share-bar">
            <div>
              <div style={{ fontWeight: 600 }}>Share by link</div>
              <div className="meta">Anyone can open this deck — no account needed.</div>
            </div>
            <button className="btn-ghost auto" disabled={link.busy} onClick={doShareLink}>
              {link.busy ? "…" : "🔗 Share link"}
            </button>
          </div>
          {link.error && <p className="error">{link.error}</p>}
          {link.url && (
            <div className="card link-share pop">
              <label>Shareable link</label>
              <div className="link-row">
                <input type="text" readOnly value={link.url} onFocus={(e) => e.target.select()} />
                <button className="btn-ghost auto" onClick={copyUrl}>{link.copied ? "Copied ✓" : "Copy"}</button>
              </div>
            </div>
          )}
          <Deck flashcards={state.deck.flashcards} quiz={state.deck.quiz} />
          {state.deck.model_used && state.deck.model_used !== "none" && (
            <p className="muted center">generated by {state.deck.model_used}</p>
          )}
        </>
      )}
    </div>
  );
}
